# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FantasyIQ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FantasyIQ
    pod 'Firebase/Auth'
    pod 'Firebase/Database'


  target 'FantasyIQTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FantasyIQUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
